name: Deploy ReactJs Application

on:
  push:
    branches:
      - main # Replace with your desired branch

jobs:
  copy-repo:
    runs-on: self-hosted # You can choose a different runner if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install --force

    - name: Check if React app is running
      run: |
          pm2 list > pm2_list.txt
          if grep -wq "client" pm2_list.txt; then
            echo "Your Node.js app is running. Stopping it..."
            pm2 stop client
            pm2 delete client
            echo "Your Node.js app has been stopped."
          else
            echo "Your Node.js app is not running."
          fi

    - name: Start React App
      run: pm2 start npm --name "client" -- start

    - name: Save PM2 process list
      run: pm2 list
